# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformed_dimensions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitGameRevenueDimension',
        ),
        migrations.AddField(
            model_name='pitgamedimension',
            name='game',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitgamedimension',
            name='oasis_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitgamedimension',
            name='pit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pitgamedimension',
            name='game_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='pitgamedimension',
            table='pitgame_revenue_dim',
        ),
    ]
