# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformed_dimensions', '0002_auto_20160926_1636'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pitgamedimension',
            table='pitgame_dim',
        ),
    ]
