# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformed_dimensions', '0003_auto_20160926_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBudgetDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_date', models.DateField()),
                ('casino', models.CharField(max_length=50, null=True)),
                ('previous_year_slot_win', models.FloatField()),
                ('budget_slot_win', models.FloatField()),
                ('budget_coin_in', models.FloatField()),
                ('budget_table_win', models.FloatField()),
                ('budget_f_and_b_revenue', models.FloatField()),
            ],
            options={
                'db_table': 'daily_budget_dim',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailybudgetdimension',
            unique_together=set([('casino', 'budget_date')]),
        ),
    ]
